blueprint:
  name: "Kontrola Midea AC LAN na podstawie temperatury i wilgotności"
  description: >
    Steruje klimatyzatorem Midea AC LAN w zależności od temperatury i wilgotności:
    chłodzi, grzeje, osusza lub przełącza na AUTO.
  domain: automation

  input:
    sensor_temperature:
      name: Czujnik temperatury
      selector:
        entity:
          domain: sensor
          device_class: temperature

    sensor_humidity:
      name: Czujnik wilgotności (opcjonalnie)
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: humidity

    climate_device:
      name: Klimatyzator (Midea AC LAN)
      selector:
        entity:
          domain: climate

    temp_target_cool:
      name: Temperatura dla chłodzenia (°C)
      selector:
        number:
          min: 16
          max: 30

    temp_target_heat:
      name: Temperatura dla grzania (°C)
      selector:
        number:
          min: 10
          max: 25

    humidity_max:
      name: Maksymalna wilgotność (%)
      default: 70
      selector:
        number:
          min: 30
          max: 90

trigger:
  - platform: state
    entity_id: !input sensor_temperature

  - platform: state
    entity_id: !input sensor_humidity

action:
  - choose:

      # 1️⃣ Wilgotność – tylko jeśli czujnik istnieje
      - conditions:
          - condition: template
            value_template: >
              {{ (inputs.sensor_humidity != '') and
                 (states(inputs.sensor_humidity) | float > inputs.humidity_max) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: dry

      # 2️⃣ Chłodzenie
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_temperature
            above: !input temp_target_cool
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: !input temp_target_cool

      # 3️⃣ Grzanie
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_temperature
            below: !input temp_target_heat
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: heat
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: !input temp_target_heat

  # 4️⃣ Domyślnie AUTO, jeśli nic nie pasuje
    default:
      - service: climate.set_hvac_mode
        target:
          entity_id: !input climate_device
        data:
          hvac_mode: auto
