blueprint:
  name: Kontrola Midea AC LAN – temperatura + wilgotność
  description: >
    Automatyczne przełączanie trybu klimatyzacji Midea (midea_ac_lan)
    w zależności od temperatury i wilgotności.
  domain: automation

  input:
    sensor_temperature:
      name: Czujnik temperatury
      selector:
        entity:
          domain: sensor
          device_class: temperature

    sensor_humidity:
      name: Czujnik wilgotności
      selector:
        entity:
          domain: sensor
          device_class: humidity

    climate_device:
      name: Klimatyzacja Midea
      selector:
        entity:
          domain: climate

    temp_target_cool:
      name: Temperatura dla chłodzenia (°C)
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: "°C"

    temp_target_heat:
      name: Temperatura dla grzania (°C)
      selector:
        number:
          min: 10
          max: 25
          unit_of_measurement: "°C"

    humidity_max:
      name: Maksymalna wilgotność (%)
      default: 70
      selector:
        number:
          min: 30
          max: 90
          unit_of_measurement: "%"

trigger:
  - platform: state
    entity_id: !input sensor_temperature

  - platform: state
    entity_id: !input sensor_humidity

condition: []

action:
  - choose:

      # --- WILGOTNOŚĆ ---
      - conditions:
          - condition: template
            value_template: >
              {{ states( !input sensor_humidity ) not in ['unknown', 'unavailable', ''] and
                 (states( !input sensor_humidity ) | float(0)) >
                 ( !input humidity_max | float(0) ) }}
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: dry

      # --- CHŁODZENIE ---
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_temperature
            above: !input temp_target_cool
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: cool
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: !input temp_target_cool

      # --- GRZANIE ---
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_temperature
            below: !input temp_target_heat
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: heat
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: !input temp_target_heat

    # --- W INNYCH PRZYPADKACH AUTO ---
    default:
      - service: climate.set_hvac_mode
        target:
          entity_id: !input climate_device
        data:
          hvac_mode: auto
