blueprint:
  name: "Kontrola Midea AC LAN — temperatura + wilgotność"
  description: >
    Automatyczne sterowanie klimatyzatorem Midea (midea_ac_lan)
    na podstawie temperatury i wilgotności.
  domain: automation
  input:
    sensor_temperature:
      name: Czujnik temperatury
      selector:
        entity:
          domain: sensor
          device_class: temperature

    sensor_humidity:
      name: Czujnik wilgotności (opcjonalnie)
      default: ""
      selector:
        entity:
          domain: sensor
          device_class: humidity
          multiple: false

    climate_device:
      name: Urządzenie klimatyzacyjne
      selector:
        entity:
          domain: climate

    temp_target_cool:
      name: Temperatura dla chłodzenia (°C)
      selector:
        number:
          min: 16
          max: 30
          unit_of_measurement: "°C"

    temp_target_heat:
      name: Temperatura dla grzania (°C)
      selector:
        number:
          min: 10
          max: 25
          unit_of_measurement: "°C"

    humidity_max:
      name: Maksymalna wilgotność (%) — tryb dry
      default: 70
      selector:
        number:
          min: 30
          max: 90
          unit_of_measurement: "%"

trigger:
  - platform: state
    entity_id: !input sensor_temperature

  - platform: state
    entity_id: !input sensor_humidity
    # Działa tylko jeśli wybrano s-humidity
    enabled: "{{ (input.sensor_humidity | string) != '' }}"

action:
  - variables:
      temp: "{{ states(input.sensor_temperature) | float(0) }}"
      hum_entity: "{{ input.sensor_humidity }}"
      hum: >
        {% if hum_entity != '' %}
        {{ states(hum_entity) | float(0) }}
        {% else %}
        -1
        {% endif %}

  - choose:

      # --- Wilgotność powyżej limitu ---
      - conditions:
          - "{{ hum_entity != '' and hum > (input.humidity_max | float) }}"
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: "dry"

      # --- Temperatura za wysoka = chłodzenie ---
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_temperature
            above: !input temp_target_cool
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: "cool"
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: !input temp_target_cool

      # --- Temperatura za niska = grzanie ---
      - conditions:
          - condition: numeric_state
            entity_id: !input sensor_temperature
            below: !input temp_target_heat
        sequence:
          - service: climate.set_hvac_mode
            target:
              entity_id: !input climate_device
            data:
              hvac_mode: "heat"
          - service: climate.set_temperature
            target:
              entity_id: !input climate_device
            data:
              temperature: !input temp_target_heat

    default:
      - service: climate.set_hvac_mode
        target:
          entity_id: !input climate_device
        data:
          hvac_mode: "auto"
